Desinstalei todos pythons

Instalei o Anaconda3-4.4.0 (All Users, e marquei para colocar no path as variáveis)
https://www.continuum.io/downloads
isso instala o Python 3.6


conda update conda
conda update python
conda install numpy
pip install opencv
pip install opencv-python


testei alguns exemplos e vi que continuam funcionando


Agora para o caffe precisa do Python 3.5


criei um ambiente para o 3.5
conda create -n py35 python=3.5 anaconda
activate py35 (volta para o 3.6 com deactivate, lista: conda info --envs)
conda config --add channels conda-forg
conda config --add channels willyd
conda install --yes cmake ninja numpy scipy protobuf six scikit-image pyyaml pydotplus graphviz
conda install ninja --yes
conda install -c menpo opencv3






Baixei o Caffé
https://github.com/BVLC/caffe/tree/windows 


C:\Projects> git clone https://github.com/BVLC/caffe.git
C:\Projects> cd caffe
C:\Projects\caffe> git checkout windows

:: Edit any of the options inside build_win.cmd to suit your needs
- fiz várias alterações em scripts\build_win.cmd
- só funciona com VS até 2015 (14)

C:\Projects\caffe> scripts\build_win.cmd






Primeiro, compilei pelo VS2015 o projeto ALL_BUILD
Depois, rodei direto pelo prompt
C:\Projects\caffe> scripts\build_win.cmd


Agora, testar o caffe
cd E:\GitHub\caffe\build\tools\Release


Agora testar o Python
python -c "import caffe;print( caffe.__version__)"


não funcionou, então


copiei a pasta caffe
E:\GitHub\caffe\python\caffe
para o anaconda, dentro de 
C:\ProgramData\Anaconda3\Lib\site-packages
C:\ProgramData\Anaconda3\envs\py35\Lib\site-packages


(segui parte deste video https://www.youtube.com/watch?v=AN2uXGRvw9E) 




Agora um teste mais efetivo
(py35) python python\classify.py examples/images/cat.jpg foo2 --gpu

Me dá o erro:
RuntimeError: Could not open file python\../models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel


Isso deve dizer que não tenho este modelo, então estou baixando um pronto de:
http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel


vou colocar na pasta:
E:\GitHub\caffe\models\bvlc_reference_caffenet


Agora o erro é:
File "E:\GitHub\caffe\python\caffe\classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "E:\GitHub\caffe\python\caffe\io.py", line 259, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.


Então, no arquivo  "E:\GitHub\caffe\python\caffe\io.py", troquei na linha 259, isso:
if ms != self.inputs[in_][1:]: raise ValueError('Mean shape incompatible with input shape.')
por:
if ms != self.inputs[in_][1:]: print(self.inputs[in_]) in_shape = self.inputs[in_][1:] m_min, m_max = mean.min(), mean.max() normal_mean = (mean - m_min) / (m_max - m_min) mean = resize_image(normal_mean.transpose((1,2,0)),in_shape[1:]).transpose((2,0,1)) * (m_max - m_min) + m_min #raise ValueError('Mean shape incompatible with input shape.')


Agora, me deu o erro:


File "E:\GitHub\caffe\python\caffe\classifier.py", line 95, in predict
    predictions = predictions.reshape((len(predictions) / 10, 10, -1))
TypeError: 'float' object cannot be interpreted as an integer


então,  "E:\GitHub\caffe\python\caffe\classifier.py", line 95, troquei:
predictions = predictions.reshape((len(predictions) / 10, 10, -1))
por:
predictions = predictions.reshape((len(predictions) // 10, 10, -1))


PRONTO, result:
Loading file: examples/images/cat.jpg
Classifying 1 inputs.
Done in 0.09 s.
Saving results into foo2


E criou um arquivo chamado foo2.npy


Mas preciso mostrar o resultado, e o arquivo acima tem apenas os valores de predição para todas as classes, sem nome de classes, então …


segui este videos e outro links por conta dos erros https://www.youtube.com/watch?v=RjRkJ5N0xPU 


adicionei no arquivo classify.py :

no início:
import pandas as pd

em (# Optional arguments.)
   # Optional arguments.
   parser.add_argument(
       "--print_results",
       action='store_true',
       help="Write output text to stdout rather than serializing to a file."
   )
   parser.add_argument(
       "--labels_file",
       default=os.path.join(pycaffe_dir,
           "../data/ilsvrc12/synset_words.txt"),
       help="Readable label definition file."
   )


e modifiquei o Classify


   # Classify.
   start = time.time()
   score = classifier.predict(inputs, not args.center_only)
   print("Done in %.2f s." % (time.time() - start))




   if args.print_results:
       with open(args.labels_file) as f:
         labels_df = pd.DataFrame([
              {
                  'synset_id': l.strip().split(' ')[0],
                  'name': ' '.join(l.strip().split(' ')[1:]).split(',')[0]
              }
              for l in f.readlines()
           ])
       labels = labels_df.sort_values('synset_id').values


       indices = (-score).argsort()[:,:5]
       predictions = labels[indices][0]


       meta = [
                  (p[0], '%.5f' % score[0][i])
                  for i, p in zip(indices[0], predictions)
              ]


       print(meta)










baixei o arquivo https://raw.githubusercontent.com/HoldenCaulfieldRye/caffe/master/data/ilsvrc12/synset_words.txt


e coloquei na pasta
E:\GitHub\caffe\data\ilsvrc12


Agora para rodar é:
(py35) E:\GitHub\caffe>python python\classify.py examples/images/cat.jpg foo2 --gpu --print_results




O resultado vai ficar assim:


Classifying 1 inputs.
Done in 0.09 s.
[('tabby', '0.27934'), ('tiger cat', '0.21915'), ('Egyptian cat', '0.16064'), ('lynx', '0.12844'), ('kit fox', '0.05155')]
Saving results into foo2




Desenhar  a rede
(py35) E:\GitHub\caffe>python python\draw_net.py models\bvlc_reference_caffenet\deploy.prototxt visualization.png




  









Baixando novos modelos
(py35) E:\GitHub\caffe>python scripts/download_model_binary.py models/bvlc_reference_rcnn_ilsvrc13




Agora DETECÇÃO  =>  NÃO FUNCIONA SEM MATLAB


baixei o modelo bvlc_reference_rcnn_ilsvrc13


criei a pasta _TEMP
E:\GitHub\caffe>mkdir _temp


cria o arquivo com as imagens
echo %cd%/images/fish-bike.jpg > _temp/det_input.txt








Rodar
E:\GitHub\caffe>python python/detect.py --crop_mode=selective_search --pretrained_model=models/bvlc_reference_rcnn_ilsvrc13/bvlc_reference_rcnn_ilsvrc13.caffemodel --model_def=models/bvlc_reference_rcnn_ilsvrc13/deploy.prototxt --raw_scale=255 _temp/det_input.txt _temp/det_output.h5




Não funcionou 
então baixo de 
https://github.com/sergeyk/selective_search_ijcv_with_python
coloquei a pasta selective_search_ijcv_with_python
em 
C:\ProgramData\Anaconda3\envs\py35\Lib\site-packages\selective_search_ijcv_with_python


Acontece que este  precisa de MatLab, e eu não tenho, estou instalando uma alternativa GNU Octave para testar


https://www.gnu.org/software/octave/download.html 




NÃO FUNCIONA SEM MATLAB